# NOTE: all port mapping are forbidden when using network_mode: host
# keep the mapping commented to show what ports are being used in this compose file
version: '3'
services:
  cassandra:
    image: cassandra:3.11
#    ports:
#      - "9042:9042"
    network_mode: host
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - '9090:9090'
    network_mode: host
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
#    ports:
#      - "2181:2181"
    network_mode: host
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    depends_on:
      - zookeeper
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: host
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
#    ports:
#      - "9200:9200"
    environment:
      - discovery.type=single-node
    network_mode: host
  cadence:
    image: ubercadence/server:master-auto-setup
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#      - "8002:8002"
#      - "8003:8003"
#      - "7933:7933"
#      - "7934:7934"
#      - "7935:7935"
#      - "7939:7939"
#      - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=localhost"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml"
      - "ENABLE_ES=true"
      - "ES_SEEDS=localhost"
      - "ES_VERSION=v7"
      - "KAFKA_SEEDS=localhost"
      - "FRONTEND_SERVICE=localhost"
      - "BIND_ON_IP=127.0.0.1"
      - "PRIMARY_FRONTEND_SERVICE=localhost"
    depends_on:
      - cassandra
      - prometheus
      - kafka
      - elasticsearch
    network_mode: host
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=localhost:7933"
#    ports:
#      - "8088:8088"
    depends_on:
      - cadence
    network_mode: host
  grafana:
    image: grafana/grafana
    user: "1000"
    depends_on:
      - prometheus
#    ports:
#      - '3000:3000'
    network_mode: host