
service:
  subscribers:
    - name: notificationAppA
      delivery:
        method: "webhook"
        webhook:
          url:
            scheme: "http"
            host: "127.0.0.1:8810"
          retryInterval: 10s # default to 1s
      comsumer:
        consumerGroup: cadence-notificationAppA-group
        consumerGroupDlqTopic: cadence-notificationAppA-group-dlq
        iniitalOffset: "newest" # or "oldest"
      filter:
        selectedDomains: # if empty, then notification messages will include all domains
          - domainA
          - domainB
  metrics:
    prometheus:
      timerType: "histogram"
      listenAddress: "127.0.0.1:8000"

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
  applications:
    notificationAppA:
      topic: cadence-visibility-dev

