
service:
  notifications:
    - applicationName: notificationAppA
      callbackURLPrefix: "http://mydomain.com/cadenceA"
      consumerGroup: cadence-notificationAppA-group
      consumerGroupDlqTopic: cadence-notificationAppA-group-dlq
      iniitalOffset: "newest" # or "oldest"
      retryInterval: 10s # default to 1s
      selectedDomains: # if empty, then notification messages will include all domains
        - domainA
        - domainB
    - applicationName: notificationAppB
      callbackURLPrefix: "http://mydomain.com/cadenceB"
      consumerGroup: cadence-notificationAppB-group
      consumerGroupDlqTopic: cadence-notificationAppB-group-dlq
      iniitalOffset: "newest" # or "oldest"
  metrics:
    prometheus:
      timerType: "histogram"
      listenAddress: "127.0.0.1:8000"

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev

